import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import subjectsRouter from "./subjects";
import coursesRouter from "./courses";
import liveClassesRouter from "./liveClasses";
import recordingsRouter from "./recordings";
import animatedVideosRouter from "./animatedVideos";
import homeworkRouter from "./homework";
import assignmentsRouter from "./assignments";
import testsRouter from "./tests";
import studentRouter from "./student";
import adminRouter from "./admin";
import teacherRouter from "./teacher";
import announcementsRouter from "./announcements";
import attendanceRouter from "./attendance";
import curriculumRouter from "./curriculum";
import syllabusRouter from "./syllabus";
import demoBatchesRouter from "./demoBatches";
import mentorRouter from "./mentor";
import mentorExtendedRouter from "./mentorExtended";
import checkinsRouter from "./checkins";
import staffRouter from "./staff";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(adminRouter);
router.use(teacherRouter);
router.use(announcementsRouter);
router.use(attendanceRouter);
router.use(curriculumRouter);
router.use(syllabusRouter);
router.use(demoBatchesRouter);
router.use(subjectsRouter);
router.use(coursesRouter);
router.use(liveClassesRouter);
router.use(recordingsRouter);
router.use(animatedVideosRouter);
router.use(homeworkRouter);
router.use(assignmentsRouter);
router.use(testsRouter);
router.use(studentRouter);
router.use(mentorRouter);
router.use(mentorExtendedRouter);
router.use(checkinsRouter);
router.use(staffRouter);

export default router;
